spring:
  application:
    name: mutant-detector
  datasource:
    driver-class-name: org.postgresql.Driver
    url: yourUrl
    username: yourUser
    password: yourPass
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    hibernate:
      ddl-auto: create

dna:
  coincidence-count: 4
  minimum-coincidences: 2

